object Form3: TForm3
  Left = 0
  Top = 0
  Caption = 'MDIChildForm2'
  ClientHeight = 381
  ClientWidth = 447
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Visible = True
  OnActivate = FormActivate
  OnClose = CloseAction
  PixelsPerInch = 96
  TextHeight = 13
end
